exports.defaultRules = function(automatic_id) {
  return [
    {
      "automatic_id": automatic_id,
      "enabled": false,
      "title": "Text my significant other when leaving work with ETA (select your work and home location)",
      "daySunday": false,
      "dayMonday": true,
      "dayTuesday": true,
      "dayWednesday": true,
      "dayThursday": true,
      "dayFriday": true,
      "daySaturday": false,
      "startTime": "4:00pm",
      "endTime": "9:00pm",
      "allDay": false,
      "automaticEvent": "ignitionOn",
      "countryCode": "1",
      "phone": "555-123-4567",
      "message": "Jane has left work.",
      "includeMap": true,
      "address": "77 Geary Street, San Francisco, CA 94108, USA",
      "radius": "130",
      "latitude": "37.787798",
      "longitude": "-122.40478009999998",
      "anywhere": false,
      "timezone": "America/Los_Angeles"
    },
    {
      "automatic_id": automatic_id,
      "enabled": false,
      "title": "Text my friend when I get home late at night (select your home location)",
      "daySunday": true,
      "dayMonday": true,
      "dayTuesday": true,
      "dayWednesday": true,
      "dayThursday": true,
      "dayFriday": true,
      "daySaturday": true,
      "startTime": "8:00pm",
      "endTime": "11:45pm",
      "allDay": false,
      "automaticEvent": "ignitionOff",
      "countryCode": "1",
      "phone": "555-123-4567",
      "message": "Jane got home.",
      "includeMap": false,
      "address": "535 Florida Street, San Francisco, CA 94110, USA",
      "radius": "130",
      "latitude": "37.762275",
      "longitude": "-122.41078500000003",
      "anywhere": false,
      "timezone": "America/Los_Angeles"
    }
  ];
}
